"""
db_sampler.py

Loads and indexes all database tables so the payload builder can draw
realistic, internally-consistent samples.

Tables used:
  customer_info.json           → customers (100 records, 4 segments)
  customer_acc_detail.json     → accounts per CIF
  session_info.json            → real session states with narratives
  restructure_offer_summary.json → offer plans generated by the advisor engine
  restructure_offer_account.json → per-account offer details
  conversation.json            → real conversation history turns
"""

from __future__ import annotations

import json
import random
from collections import defaultdict
from pathlib import Path
from typing import Optional

# ---------------------------------------------------------------------------
# Default DB path — same database/ folder used by the webapp
# ---------------------------------------------------------------------------
_DEFAULT_DB = Path(__file__).parent / "database"


class DatabaseSampler:
    def __init__(self, db_dir: Path = _DEFAULT_DB):
        self.db_dir = db_dir
        self._load()

    def _load(self):
        def _read(name: str):
            return json.loads((self.db_dir / name).read_text(encoding="utf-8"))

        self.customers: list[dict] = _read("customer_info.json")
        self.accounts: list[dict] = _read("customer_acc_detail.json")
        self.sessions: list[dict] = _read("session_info.json")
        self.offer_summaries: list[dict] = _read("restructure_offer_summary.json")
        self.offer_accounts: list[dict] = _read("restructure_offer_account.json")
        self.conversations: list[dict] = _read("conversation.json")

        # Index: CIF → customer
        self.cust_by_cif: dict[str, dict] = {c["cif"]: c for c in self.customers}

        # Index: CIF → list[account]
        self.acc_by_cif: dict[str, list[dict]] = defaultdict(list)
        for a in self.accounts:
            self.acc_by_cif[a["cif"]].append(a)

        # Index: segment → list[customer]
        self.cust_by_seg: dict[str, list[dict]] = defaultdict(list)
        for c in self.customers:
            self.cust_by_seg[c["customerSegment"]].append(c)

        # Index: sessionId → session_info record
        self.session_by_id: dict[str, dict] = {s["sessionId"]: s for s in self.sessions}

        # Index: sessionId → list[offer_summary]
        self.offers_by_session: dict[str, list[dict]] = defaultdict(list)
        for o in self.offer_summaries:
            self.offers_by_session[o["sessionId"]].append(o)

        # Index: sessionId → list[offer_account]
        self.offer_acc_by_session: dict[str, list[dict]] = defaultdict(list)
        for oa in self.offer_accounts:
            self.offer_acc_by_session[oa["sessionId"]].append(oa)

        # Index: sessionId → list[conversation turn]
        self.conv_by_session: dict[str, list[dict]] = defaultdict(list)
        for turn in sorted(self.conversations, key=lambda t: t["createdAt"]):
            self.conv_by_session[turn["sessionId"]].append(turn)

        self.segments = list(self.cust_by_seg.keys())

    # ── Customer helpers ──────────────────────────────────────────────────────

    def random_customer(self, segment: Optional[str] = None) -> dict:
        pool = self.cust_by_seg[segment] if segment else self.customers
        return random.choice(pool)

    def get_accounts(self, cif: str) -> list[dict]:
        return self.acc_by_cif.get(cif, [])

    # ── Session helpers ───────────────────────────────────────────────────────

    def random_session(self) -> dict:
        return random.choice(self.sessions)

    def get_offers_for_session(self, session_id: str) -> list[dict]:
        return self.offers_by_session.get(session_id, [])

    def get_offer_accounts_for_session(self, session_id: str) -> list[dict]:
        return self.offer_acc_by_session.get(session_id, [])

    def get_conversation(self, session_id: str) -> list[dict]:
        return self.conv_by_session.get(session_id, [])

    # ── Offer helpers ─────────────────────────────────────────────────────────

    def build_offer_soln_entry(self, offer_summary: dict, offer_acc_records: list[dict]) -> dict:
        """
        Build an offerSoln entry in the format the advisor engine produces.
        Combines fields from restructure_offer_summary + restructure_offer_account.
        """
        plan_id = offer_summary["planId"]
        acc_records = [r for r in offer_acc_records if r["planId"] == plan_id]

        acc_nos = ", ".join(r["refAccNo"] for r in acc_records)
        installment = acc_records[0]["installment"] if acc_records else offer_summary.get("installment", 0)
        installment_y2 = acc_records[0].get("installmentY2") if acc_records else None
        installment_y3 = acc_records[0].get("installmentY3") if acc_records else None

        entry = {
            "planId": plan_id,
            "planDesc": offer_summary.get("planDesc", ""),
            "solutionDesc": offer_summary.get("solutionDesc", ""),
            "refAccNo": acc_nos or offer_summary.get("refAccNo", ""),
            "term": offer_summary.get("term", 0),
            "installment": round(installment, 2),
            "totalExpInt": round(offer_summary.get("totalExpInt", 0), 2),
            "plan_desc": offer_summary.get("planDesc", ""),
            "source_desc": offer_summary.get("solutionDesc", ""),
            "accounts": acc_nos or offer_summary.get("refAccNo", ""),
            "cnt_eligible": len(acc_records) or 1,
            "cnt_total": len(acc_records) or 1,
            "total_os": round(sum(r.get("os", 0) for r in acc_records), 2),
            "new_inst": round(installment, 2),
            "int_rate_new": f"{round((acc_records[0].get('intRate', 0) if acc_records else 0) * 100, 0):.0f}%",
            "term_change": f"{offer_summary.get('term', 0)} งวด",
            "int_total_change": f"{round(offer_summary.get('totalExpInt', 0), 0):.0f} บาท",
        }

        if installment_y2 is not None:
            entry["maxPaymentY2"] = round(installment_y2, 2)
        if installment_y3 is not None:
            entry["maxPaymentY3"] = round(installment_y3, 2)

        return entry

    def build_offer_card_message(self, offer_entry: dict) -> str:
        """Build the JSON message string for an offerCard selection."""
        return json.dumps([{
            "jsonType": "offerCard",
            "planId": offer_entry["planId"],
            "offerCard": offer_entry,
        }], ensure_ascii=False)
